Install ffmpeg from git master

diff --git a/scripts/install-ffmpeg b/scripts/install-ffmpeg
--- a/scripts/install-ffmpeg
+++ b/scripts/install-ffmpeg
@@ -1,15 +1,56 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir> <env-dir>
 
-# set -e: don't tolerate non-zero exit status for any command
-set -e
+# adapted from https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest/blob/master/bin/compile
 
-indent() {
-  sed -u 's/^/       /'
+header() {
+  echo "" || true
+  echo "-----> $*" || true
+} 
+
+output() {
+  while IFS= read -r LINE; do
+    # do not indent headers that are being piped through the output
+    if [[ "$LINE" =~ ^-----\>.* ]]; then
+      echo "$LINE" || true
+    else
+      echo "       $LINE" || true
+    fi
+  done
 }
 
-echo "-----> Install ffmpeg"
-BUILD_DIR="/usr/local/bin"
-DOWNLOAD_URL="https://s3-eu-west-1.amazonaws.com/denkungsart/ffmpeg-release-64bit-static.tar.xz"
-echo "DOWNLOAD_URL = " $DOWNLOAD_URL | indent
-cd $BUILD_DIR || exit
-curl -L --silent $DOWNLOAD_URL | tar xJ --strip-components=1
+header "Installing ffmpeg"
+
+BUILD_DIR=${1:-}
+FFMPEG_ARCHIVE_NAME="ffmpeg.tar.xz"
+
+cd $BUILD_DIR
+mkdir -p ffmpeg
+cd ffmpeg
+
+if [[ -z $FFMPEG_DOWNLOAD_URL ]]; then
+  echo "Variable FFMPEG_DOWNLOAD_URL isn't set, using default value" | output
+  FFMPEG_DOWNLOAD_URL="https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz"
+fi
+
+echo "Downloading $FFMPEG_DOWNLOAD_URL" | output
+
+code=$(curl "$FFMPEG_DOWNLOAD_URL" -L --silent --fail --retry 5 --retry-max-time 15 -o ./$FFMPEG_ARCHIVE_NAME --write-out "%{http_code}")
+
+if [ "$code" != "200" ]; then
+  echo "Unable to download ffmpeg: $code" | output && exit 1
+fi
+
+echo "Unpacking the archive" | output
+
+tar xJf "./$FFMPEG_ARCHIVE_NAME" --strip-components=1
+
+if [ "$?" != "0" ]; then
+  echo "Failed to unpack" | output && exit 1
+fi
+
+rm $FFMPEG_ARCHIVE_NAME
+
+mv ffmpeg /usr/local/bin
+
+echo "Installation successful" | output
